basic:
  # experiment_name
  exp: Breast_Fully_Supervised
  # whether use deterministic training
  deterministic: true
  # random seed
  seed: 1337
  # labeled data
  labeled_num: 25
  device: GPU
model:
  name: unet_3D
  in_channels: 1
  out_channels:
  class_num: 2
loss:
  name:
optimizer:
  learning_rate: 0.01
  weight_decay:
eval_metric:
  name:
lr_scheduler:
  name:
  factor:
  patience:
trainer:
  checkpoint_dir: CHECKPOINT_DIR
  resume: null
  pre_trained: null
  validate_after_iters: 2000
  log_after_iters: 100
  max_num_epochs: 200
  max_num_iterations: 30000
loaders:
  dataset: StandardHDF5Dataset
  num_workers: 1
  batch_size: 1
  raw_internal_path:
  label_internal_path:
  train:
    file_paths:
      - TRAIN_DIR
    slice_builder:
      name:
      patch_shape:
      stride_shape:
    transformer:
      raw:
        - name:
      label:
        - name:
  val:
    file_paths:
      - TRAIN_DIR
      slice_builder:
        name:
        patch_shape:
        stride_shape:
      transformer:
        raw:
          - name:
        label:
          - name: